package vistas;

/**
 *
 * @author Jiss
 */
import java.awt.Image;
import java.awt.Toolkit;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modelo.Informe;
import modelo.InformesDAO;

public class InformeForm extends javax.swing.JFrame {

    InformesDAO dao = new InformesDAO();
    Informe p = new Informe();
    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableCellRenderer centrarTabla = new DefaultTableCellRenderer();
    SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
    Calendar clndr;

    public InformeForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        FormatoDeFechas();
        limpiarFormulario();
        listar();
    }
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon2.png"));
        return retValue;
    }
    
    private void limpiarFormulario(){
        jTextCodigo.setEnabled(false);
        jTexCantidadBoletas.setEnabled(false);
        jTexCantidadBoletas.setText("");
        jTextCantidadTickets.setEnabled(false);
        jTextCantidadTickets.setText("");
        jTextTotalVenta.setEnabled(false);
        jTextTotalVenta.setText("");
        jBGenerar.setEnabled(false);
        jBGuardar.setEnabled(false);
        jDDesde.setEnabled(false);
        jDHasta.setEnabled(false);
        jDDesde.setCalendar(null);
        jDHasta.setCalendar(null);
    }
    private void FormatoDeFechas(){        
        jDateFechaBuscar.setEnabled(false);
        jDateFechaBuscar.setDateFormatString("dd/MM/yyyy");
        jDfecha.setEnabled(false);
        jDfecha.setDateFormatString("dd/MM/yyyy");
        jDDesde.setEnabled(false);
        jDDesde.setDateFormatString("dd/MM/yyyy");
        jDHasta.setEnabled(false);
        jDHasta.setDateFormatString("dd/MM/yyyy");        
    }

    private void listar() {
        List<Informe> lista = dao.listar();

        modelo = (DefaultTableModel) tabla.getModel();
        Object[] ob = new Object[7];
        for (int i = 0; i < lista.size(); i++) {
            ob[0] = lista.get(i).getCorrelativo();
            ob[1] = lista.get(i).getFechaInforme();
            ob[2] = lista.get(i).getCantidadBoletas();
            ob[3] = lista.get(i).getCantidadTicket();
            ob[4] = lista.get(i).getTotalVenta();
            ob[5] = lista.get(i).getFechaInicio();
            ob[6] = lista.get(i).getFechaTermino();
            modelo.addRow(ob);
        }
        centrarTabla.setHorizontalAlignment(JLabel.LEFT);
        tabla.getColumnModel().getColumn(0).setCellRenderer(centrarTabla);
        tabla.setModel(modelo);
        //ocultando filas (las filas son necesarias para cargar los detalles de los informes NO BORRAR)
        tabla.getColumn("Cantidad Boletas").setMinWidth(0);
        tabla.getColumn("Cantidad Boletas").setMaxWidth(0);
        tabla.getColumn("Cantidad Boletas").setWidth(0);
        
        tabla.getColumn("Cantidad Tickets").setMinWidth(0);
        tabla.getColumn("Cantidad Tickets").setMaxWidth(0);
        tabla.getColumn("Cantidad Tickets").setWidth(0);
        
        tabla.getColumn("Total Ventas").setMinWidth(0);
        tabla.getColumn("Total Ventas").setMaxWidth(0);
        tabla.getColumn("Total Ventas").setWidth(0);
        
        tabla.getColumn("Fecha Inicio").setMinWidth(0);
        tabla.getColumn("Fecha Inicio").setMaxWidth(0);
        tabla.getColumn("Fecha Inicio").setWidth(0);
        
        tabla.getColumn("Fecha Termino").setMinWidth(0);
        tabla.getColumn("Fecha Termino").setMaxWidth(0);
        tabla.getColumn("Fecha Termino").setWidth(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        jLabelInformeTitle = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jRadioCodigo = new javax.swing.JRadioButton();
        jRadioFecha = new javax.swing.JRadioButton();
        jBBuscar = new javax.swing.JButton();
        jLabelInformeTitle2 = new javax.swing.JLabel();
        jTextCodigo = new javax.swing.JTextField();
        jDateFechaBuscar = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabelInformeTitle1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelInformeTitle3 = new javax.swing.JLabel();
        jDDesde = new com.toedter.calendar.JDateChooser();
        jLabelDesde = new javax.swing.JLabel();
        jLabelHasta = new javax.swing.JLabel();
        jDHasta = new com.toedter.calendar.JDateChooser();
        jLabelDesde1 = new javax.swing.JLabel();
        jDfecha = new com.toedter.calendar.JDateChooser();
        jLabelDesde2 = new javax.swing.JLabel();
        jLabelDesde3 = new javax.swing.JLabel();
        jLabelDesde4 = new javax.swing.JLabel();
        jTexCantidadBoletas = new javax.swing.JTextField();
        jTextCantidadTickets = new javax.swing.JTextField();
        jTextTotalVenta = new javax.swing.JTextField();
        jBGenerar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuVentas = new javax.swing.JMenu();
        jMenuEdicion = new javax.swing.JMenu();
        jMenuItemProductos = new javax.swing.JMenuItem();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenuInformes = new javax.swing.JMenu();
        jMenuItemInfDiario = new javax.swing.JMenuItem();
        jMenuItemInfMensual = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(225, 139, 34));

        Logo.setBackground(new java.awt.Color(225, 139, 34));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoSmall.png"))); // NOI18N

        jLabelInformeTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelInformeTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInformeTitle.setText("INFORME VENTAS");

        jPanel4.setBackground(new java.awt.Color(184, 115, 30));

        buttonGroup1.add(jRadioCodigo);
        jRadioCodigo.setText("Codigo");
        jRadioCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCodigoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioFecha);
        jRadioFecha.setText("Fecha");
        jRadioFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioFechaActionPerformed(evt);
            }
        });

        jBBuscar.setText("Buscar");

        jLabelInformeTitle2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelInformeTitle2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInformeTitle2.setText("Buscador");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jRadioFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateFechaBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioCodigo)
                            .addComponent(jLabelInformeTitle2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabelInformeTitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioCodigo)
                    .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioFecha)
                    .addComponent(jDateFechaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBBuscar)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInformeTitle))
                .addGap(18, 18, 18)
                .addComponent(Logo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabelInformeTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(225, 139, 34));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Correlativo", "Fecha Informe", "Cantidad Boletas", "Cantidad Tickets", "Total Ventas", "Fecha Inicio", "Fecha Termino"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabelInformeTitle1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelInformeTitle1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInformeTitle1.setText("INFORMES");

        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelInformeTitle1)
                        .addGap(53, 53, 53)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInformeTitle1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(225, 139, 34));

        jLabelInformeTitle3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelInformeTitle3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInformeTitle3.setText("DETALLE INFORME");

        jLabelDesde.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDesde.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDesde.setText("Desde");

        jLabelHasta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelHasta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHasta.setText("Hasta");

        jLabelDesde1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDesde1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDesde1.setText("Fecha");

        jLabelDesde2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDesde2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDesde2.setText("Cantidad de Boletas");

        jLabelDesde3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDesde3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDesde3.setText("Cantidad de Tickets");

        jLabelDesde4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDesde4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDesde4.setText("Total de Ventas");

        jBGenerar.setText("Generar Informe");
        jBGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGenerarActionPerformed(evt);
            }
        });

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelInformeTitle3)
                    .addComponent(jLabelDesde1)
                    .addComponent(jLabelDesde3)
                    .addComponent(jLabelDesde4)
                    .addComponent(jLabelDesde2)
                    .addComponent(jDfecha, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                    .addComponent(jLabelDesde)
                    .addComponent(jLabelHasta)
                    .addComponent(jDDesde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDHasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTexCantidadBoletas)
                    .addComponent(jTextCantidadTickets)
                    .addComponent(jTextTotalVenta)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jBGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInformeTitle3)
                .addGap(18, 18, 18)
                .addComponent(jLabelDesde1)
                .addGap(18, 18, 18)
                .addComponent(jDfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDesde)
                .addGap(13, 13, 13)
                .addComponent(jDDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelHasta)
                .addGap(18, 18, 18)
                .addComponent(jDHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDesde2)
                .addGap(18, 18, 18)
                .addComponent(jTexCantidadBoletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDesde3)
                .addGap(18, 18, 18)
                .addComponent(jTextCantidadTickets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDesde4)
                .addGap(18, 18, 18)
                .addComponent(jTextTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGenerar)
                    .addComponent(jBGuardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));

        jMenuVentas.setForeground(new java.awt.Color(255, 255, 255));
        jMenuVentas.setText("Ventas");
        jMenuVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuVentasMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuVentas);

        jMenuEdicion.setForeground(new java.awt.Color(255, 255, 255));
        jMenuEdicion.setText("Edición");

        jMenuItemProductos.setText("Productos");
        jMenuItemProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProductosActionPerformed(evt);
            }
        });
        jMenuEdicion.add(jMenuItemProductos);

        jMenuItemUsuarios.setText("Usuarios");
        jMenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosActionPerformed(evt);
            }
        });
        jMenuEdicion.add(jMenuItemUsuarios);

        jMenuBar1.add(jMenuEdicion);

        jMenuInformes.setForeground(new java.awt.Color(255, 255, 255));
        jMenuInformes.setText("Informes");

        jMenuItemInfDiario.setText("Diario");
        jMenuInformes.add(jMenuItemInfDiario);

        jMenuItemInfMensual.setText("Mensual");
        jMenuItemInfMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInfMensualActionPerformed(evt);
            }
        });
        jMenuInformes.add(jMenuItemInfMensual);

        jMenuBar1.add(jMenuInformes);

        jMenuSalir.setForeground(new java.awt.Color(255, 255, 255));
        jMenuSalir.setText("Salir");
        jMenuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCodigoActionPerformed
        jTextCodigo.setEnabled(true);
        jDateFechaBuscar.setEnabled(false);
        jDateFechaBuscar.setCalendar(null);

    }//GEN-LAST:event_jRadioCodigoActionPerformed

    private void jRadioFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioFechaActionPerformed
        jTextCodigo.setEnabled(false);
        jDateFechaBuscar.setEnabled(true);
        jTextCodigo.setText("");
    }//GEN-LAST:event_jRadioFechaActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        int fila = tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una Fila");
        } else {
            limpiarFormulario();
            int TBoleta =  (int) tabla.getValueAt(fila, 2);
            int TTicket =  (int) tabla.getValueAt(fila, 3);
            int TVenta =  (int) tabla.getValueAt(fila, 4);
            jTexCantidadBoletas.setText(""+TBoleta);
            jTextCantidadTickets.setText(""+TTicket);
            jTextTotalVenta.setText(""+TVenta);
            String fechahoy = (String)LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            try {
                java.util.Date fechaHoy = new SimpleDateFormat("dd/MM/yyyy").parse(fechahoy);
                jDfecha.setDate(fechaHoy);
                java.util.Date fechaDesde = new SimpleDateFormat("dd/MM/yyyy").parse(tabla.getValueAt(fila, 5).toString());
                jDDesde.setDate(fechaDesde);
                java.util.Date fechaHasta = new SimpleDateFormat("dd/MM/yyyy").parse(tabla.getValueAt(fila, 6).toString());
                jDHasta.setDate(fechaHasta);
            } catch (ParseException ex) {
                Logger.getLogger(InformeForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println(fechahoy);
            
        }
    }//GEN-LAST:event_tablaMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //limpiar formulario
        limpiarFormulario();
        jDHasta.setEnabled(true);
        jDDesde.setEnabled(true);
        jBGenerar.setEnabled(true);
        //esperar ingreso de fechas
        //hacer consulta con valores
        //guardar consultas por dao
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGenerarActionPerformed
        jBGenerar.setEnabled(false);
        jBGuardar.setEnabled(true);
        jDDesde.setEnabled(false);
        jDHasta.setEnabled(false);
    }//GEN-LAST:event_jBGenerarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        //ejecutar guardado
        limpiarFormulario();
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jMenuVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuVentasMouseClicked
         this.setVisible(false);

        VentaForm admP = new VentaForm();
        admP.setVisible(true);
    }//GEN-LAST:event_jMenuVentasMouseClicked

    private void jMenuItemProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProductosActionPerformed
       this.setVisible(false);

        ProductoForm admP = new ProductoForm();
        admP.setVisible(true);
    }//GEN-LAST:event_jMenuItemProductosActionPerformed

    private void jMenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosActionPerformed
        this.setVisible(false);
        UsuariosForm admP = new UsuariosForm();
        admP.setVisible(true);
    }//GEN-LAST:event_jMenuItemUsuariosActionPerformed

    private void jMenuItemInfMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInfMensualActionPerformed
        this.setVisible(false);
        InformeForm admP = new InformeForm();
        admP.setVisible(true);
    }//GEN-LAST:event_jMenuItemInfMensualActionPerformed

    private void jMenuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenuSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformeForm().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBGenerar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDDesde;
    private com.toedter.calendar.JDateChooser jDHasta;
    private com.toedter.calendar.JDateChooser jDateFechaBuscar;
    private com.toedter.calendar.JDateChooser jDfecha;
    private javax.swing.JLabel jLabelDesde;
    private javax.swing.JLabel jLabelDesde1;
    private javax.swing.JLabel jLabelDesde2;
    private javax.swing.JLabel jLabelDesde3;
    private javax.swing.JLabel jLabelDesde4;
    private javax.swing.JLabel jLabelHasta;
    private javax.swing.JLabel jLabelInformeTitle;
    private javax.swing.JLabel jLabelInformeTitle1;
    private javax.swing.JLabel jLabelInformeTitle2;
    private javax.swing.JLabel jLabelInformeTitle3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdicion;
    private javax.swing.JMenu jMenuInformes;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemInfDiario;
    private javax.swing.JMenuItem jMenuItemInfMensual;
    private javax.swing.JMenuItem jMenuItemProductos;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JMenu jMenuVentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioCodigo;
    private javax.swing.JRadioButton jRadioFecha;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTexCantidadBoletas;
    private javax.swing.JTextField jTextCantidadTickets;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextTotalVenta;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
